/**
 * Builtin Skill Library - 30 pre-built skills for the OPC Agent Marketplace
 */
import type { MarketplaceSkill } from '../types';

export const BUILTIN_SKILLS: MarketplaceSkill[] = [
  // === Productivity (效率工具) ===
  {
    id: 'note-assistant',
    name: 'Note Assistant',
    nameZh: '笔记助手',
    description: 'Automatically organize conversation highlights and key points',
    descriptionZh: '自动整理对话要点，生成结构化笔记',
    category: 'productivity',
    icon: '📝',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['create_note', 'summarize_conversation', 'list_notes'],
    systemPrompt: 'You are a note-taking assistant. Extract key points, action items, and decisions from conversations. Format them as structured notes with headers and bullet points.',
  },
  {
    id: 'calendar-manager',
    name: 'Calendar Manager',
    nameZh: '日程管理',
    description: 'Create, query, and manage calendar events',
    descriptionZh: '创建、查询和管理日程事件',
    category: 'productivity',
    icon: '📅',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['create_event', 'list_events', 'delete_event', 'update_event'],
    systemPrompt: 'You are a calendar management assistant. Help users create, modify, and query calendar events. Parse natural language dates and times.',
  },
  {
    id: 'email-assistant',
    name: 'Email Assistant',
    nameZh: '邮件助手',
    description: 'Draft, reply, and manage emails with AI',
    descriptionZh: '智能写邮件、回邮件',
    category: 'productivity',
    icon: '📧',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['draft_email', 'reply_email', 'summarize_email'],
    systemPrompt: 'You are an email assistant. Help draft professional emails, compose replies, and summarize email threads. Match the appropriate tone for business or casual contexts.',
  },
  {
    id: 'todo-manager',
    name: 'Todo Manager',
    nameZh: '待办管理',
    description: 'Manage TODO lists with priorities and deadlines',
    descriptionZh: '管理待办事项，支持优先级和截止日期',
    category: 'productivity',
    icon: '✅',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['add_todo', 'list_todos', 'complete_todo', 'delete_todo'],
    systemPrompt: 'You are a task management assistant. Help users create, organize, prioritize, and track their TODO items.',
  },
  {
    id: 'reminder',
    name: 'Reminder',
    nameZh: '提醒器',
    description: 'Set and manage reminders',
    descriptionZh: '设置各类提醒，到时通知',
    category: 'productivity',
    icon: '🔔',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['set_reminder', 'list_reminders', 'cancel_reminder'],
    systemPrompt: 'You are a reminder assistant. Help users set, manage, and cancel reminders with natural language time expressions.',
  },

  // === Knowledge (知识工具) ===
  {
    id: 'reading-summary',
    name: 'Reading Summary',
    nameZh: '阅读摘要',
    description: 'Summarize articles, web pages, and documents',
    descriptionZh: '总结文章、网页、文档的核心内容',
    category: 'knowledge',
    icon: '📚',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['summarize_text', 'extract_key_points', 'generate_outline'],
    systemPrompt: 'You are a reading assistant. Summarize long texts, extract key points, and generate structured outlines. Support multiple languages.',
  },
  {
    id: 'knowledge-search',
    name: 'Knowledge Search',
    nameZh: '知识搜索',
    description: 'Search through learned knowledge base',
    descriptionZh: '搜索已学习的知识库',
    category: 'knowledge',
    icon: '🔍',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['search_knowledge', 'add_knowledge', 'list_topics'],
    systemPrompt: 'You are a knowledge search assistant. Help users find information from their personal knowledge base and add new entries.',
  },
  {
    id: 'dictionary-translator',
    name: 'Dictionary & Translator',
    nameZh: '词典翻译',
    description: 'Multi-language translation and dictionary lookup',
    descriptionZh: '多语言翻译和词典查询',
    category: 'knowledge',
    icon: '📖',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['translate', 'define_word', 'detect_language'],
    systemPrompt: 'You are a translation and dictionary assistant. Translate between languages, explain word meanings, provide usage examples, and detect languages.',
  },
  {
    id: 'calculator',
    name: 'Calculator',
    nameZh: '计算器',
    description: 'Mathematical calculations and unit conversions',
    descriptionZh: '数学计算、单位换算',
    category: 'knowledge',
    icon: '🧮',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['calculate', 'convert_units', 'solve_equation'],
    systemPrompt: 'You are a math assistant. Perform calculations, convert units, solve equations, and explain mathematical concepts step by step.',
  },
  {
    id: 'data-analysis',
    name: 'Data Analysis',
    nameZh: '数据分析',
    description: 'Analyze CSV data, generate statistics and insights',
    descriptionZh: 'CSV 数据分析，生成统计和洞察',
    category: 'knowledge',
    icon: '📊',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['analyze_csv', 'generate_chart', 'statistical_summary'],
    systemPrompt: 'You are a data analysis assistant. Parse CSV files, compute statistics, identify trends, and provide data-driven insights.',
  },

  // === Creative (创作工具) ===
  {
    id: 'writing-assistant',
    name: 'Writing Assistant',
    nameZh: '写作助手',
    description: 'Help with various writing styles and formats',
    descriptionZh: '各种文体写作辅助',
    category: 'creative',
    icon: '✍️',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['write_article', 'improve_text', 'change_tone'],
    systemPrompt: 'You are a writing assistant. Help with essays, blog posts, stories, and other writing. Improve grammar, style, and clarity. Adapt to different tones and formats.',
  },
  {
    id: 'image-description',
    name: 'Image Description',
    nameZh: '图片描述',
    description: 'Describe and analyze images in detail',
    descriptionZh: '详细描述和分析图片内容',
    category: 'creative',
    icon: '🎨',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['describe_image', 'analyze_visual', 'generate_alt_text'],
    systemPrompt: 'You are an image analysis assistant. Describe images in detail, analyze visual elements, composition, colors, and generate accessible alt text.',
  },
  {
    id: 'social-media',
    name: 'Social Media',
    nameZh: '社交媒体',
    description: 'Generate social media posts and content',
    descriptionZh: '生成社交媒体帖文和内容',
    category: 'creative',
    icon: '📱',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['create_post', 'generate_hashtags', 'adapt_platform'],
    systemPrompt: 'You are a social media content creator. Generate engaging posts for Twitter, LinkedIn, Instagram, and other platforms. Create hashtags and adapt content for each platform.',
  },
  {
    id: 'report-generator',
    name: 'Report Generator',
    nameZh: '报告生成',
    description: 'Automatically generate structured reports',
    descriptionZh: '自动生成结构化报告',
    category: 'creative',
    icon: '📄',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['generate_report', 'create_executive_summary', 'format_report'],
    systemPrompt: 'You are a report generation assistant. Create structured reports with executive summaries, data sections, and recommendations. Support various formats.',
  },
  {
    id: 'copywriting',
    name: 'Copywriting',
    nameZh: '文案创作',
    description: 'Create marketing copy and ad content',
    descriptionZh: '营销文案和广告内容创作',
    category: 'creative',
    icon: '💌',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['write_copy', 'generate_slogan', 'ab_test_copy'],
    systemPrompt: 'You are a copywriting assistant. Create compelling marketing copy, slogans, product descriptions, and ad content. Apply AIDA and other frameworks.',
  },

  // === Developer (开发工具) ===
  {
    id: 'code-assistant',
    name: 'Code Assistant',
    nameZh: '代码助手',
    description: 'Write, review, and explain code',
    descriptionZh: '写代码、代码审查、代码解释',
    category: 'developer',
    icon: '💻',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['write_code', 'review_code', 'explain_code', 'refactor_code'],
    systemPrompt: 'You are a code assistant. Write clean, efficient code in any language. Review code for bugs and improvements. Explain complex code clearly.',
  },
  {
    id: 'debug-assistant',
    name: 'Debug Assistant',
    nameZh: 'Debug 助手',
    description: 'Help debug code issues and errors',
    descriptionZh: '帮助调试代码问题和错误',
    category: 'developer',
    icon: '🐛',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['analyze_error', 'suggest_fix', 'trace_bug'],
    systemPrompt: 'You are a debugging assistant. Analyze error messages, stack traces, and code to identify bugs. Suggest fixes and explain root causes.',
  },
  {
    id: 'api-tester',
    name: 'API Tester',
    nameZh: 'API 测试',
    description: 'Test and debug API endpoints',
    descriptionZh: '测试和调试 API 接口',
    category: 'developer',
    icon: '📋',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['test_api', 'generate_curl', 'mock_response'],
    systemPrompt: 'You are an API testing assistant. Help construct API requests, generate curl commands, test endpoints, and analyze responses.',
  },
  {
    id: 'database-query',
    name: 'Database Query',
    nameZh: '数据库查询',
    description: 'Generate and optimize SQL queries',
    descriptionZh: 'SQL 查询生成和优化',
    category: 'developer',
    icon: '🗄️',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['generate_sql', 'optimize_query', 'explain_schema'],
    systemPrompt: 'You are a database assistant. Generate SQL queries from natural language, optimize slow queries, and explain database schemas.',
  },
  {
    id: 'dependency-checker',
    name: 'Dependency Checker',
    nameZh: '依赖检查',
    description: 'Check dependencies for security vulnerabilities',
    descriptionZh: '检查依赖包的安全漏洞',
    category: 'developer',
    icon: '📦',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['check_deps', 'find_vulnerabilities', 'suggest_updates'],
    systemPrompt: 'You are a dependency security assistant. Analyze project dependencies, identify known vulnerabilities, and suggest safe update paths.',
  },

  // === Lifestyle (生活工具) ===
  {
    id: 'recipe-recommender',
    name: 'Recipe Recommender',
    nameZh: '食谱推荐',
    description: 'Recommend recipes based on available ingredients',
    descriptionZh: '根据现有食材推荐食谱',
    category: 'lifestyle',
    icon: '🍳',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['find_recipe', 'substitute_ingredient', 'meal_plan'],
    systemPrompt: 'You are a cooking assistant. Recommend recipes based on available ingredients, suggest substitutions, and create meal plans.',
  },
  {
    id: 'fitness-planner',
    name: 'Fitness Planner',
    nameZh: '健身计划',
    description: 'Generate personalized fitness plans',
    descriptionZh: '生成个性化健身计划',
    category: 'lifestyle',
    icon: '🏋️',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['create_workout', 'track_progress', 'suggest_exercise'],
    systemPrompt: 'You are a fitness planning assistant. Create personalized workout plans, track progress, and suggest exercises based on goals and fitness level.',
  },
  {
    id: 'expense-tracker',
    name: 'Expense Tracker',
    nameZh: '记账助手',
    description: 'Track income and expenses',
    descriptionZh: '收支记录和预算管理',
    category: 'lifestyle',
    icon: '💰',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['add_expense', 'add_income', 'get_summary', 'set_budget'],
    systemPrompt: 'You are a personal finance assistant. Track expenses and income, categorize transactions, and provide spending summaries and budget advice.',
  },
  {
    id: 'weather-query',
    name: 'Weather Query',
    nameZh: '天气查询',
    description: 'Get weather forecasts for any location',
    descriptionZh: '查询任意地点的天气预报',
    category: 'lifestyle',
    icon: '🌤️',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['get_weather', 'weather_forecast', 'weather_alerts'],
    systemPrompt: 'You are a weather assistant. Provide current weather conditions, forecasts, and weather alerts for any location worldwide.',
  },
  {
    id: 'travel-planner',
    name: 'Travel Planner',
    nameZh: '旅行规划',
    description: 'Plan trips and create itineraries',
    descriptionZh: '旅行行程规划和安排',
    category: 'lifestyle',
    icon: '🗺️',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['plan_trip', 'suggest_destination', 'create_itinerary'],
    systemPrompt: 'You are a travel planning assistant. Help plan trips, create detailed itineraries, suggest destinations, and provide travel tips.',
  },

  // === Business (业务工具) ===
  {
    id: 'customer-followup',
    name: 'Customer Follow-up',
    nameZh: '客户跟进',
    description: 'CRM-like customer tracking and follow-ups',
    descriptionZh: '客户关系管理，跟进记录',
    category: 'business',
    icon: '🤝',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['add_customer', 'log_interaction', 'schedule_followup', 'list_customers'],
    systemPrompt: 'You are a CRM assistant. Track customer interactions, schedule follow-ups, manage contact information, and provide relationship insights.',
  },
  {
    id: 'market-analysis',
    name: 'Market Analysis',
    nameZh: '市场分析',
    description: 'Industry and market analysis',
    descriptionZh: '行业和市场分析',
    category: 'business',
    icon: '📈',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['analyze_market', 'competitor_report', 'trend_analysis'],
    systemPrompt: 'You are a market analysis assistant. Analyze industry trends, competitive landscape, and market opportunities. Provide data-driven insights.',
  },
  {
    id: 'contract-review',
    name: 'Contract Review',
    nameZh: '合同审查',
    description: 'Review contracts and highlight key clauses',
    descriptionZh: '审查合同，标注关键条款和风险',
    category: 'business',
    icon: '📑',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['review_contract', 'extract_clauses', 'risk_assessment'],
    systemPrompt: 'You are a contract review assistant. Analyze contracts, highlight key clauses, identify potential risks, and suggest improvements.',
  },
  {
    id: 'interview-prep',
    name: 'Interview Prep',
    nameZh: '面试准备',
    description: 'Mock interviews and preparation',
    descriptionZh: '模拟面试和面试准备',
    category: 'business',
    icon: '💼',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['mock_interview', 'generate_questions', 'evaluate_answer'],
    systemPrompt: 'You are an interview preparation assistant. Conduct mock interviews, generate relevant questions, and provide feedback on answers.',
  },
  {
    id: 'okr-manager',
    name: 'OKR Manager',
    nameZh: 'OKR 管理',
    description: 'Manage objectives and key results',
    descriptionZh: '目标和关键结果管理',
    category: 'business',
    icon: '🎯',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['create_okr', 'track_progress', 'review_okrs', 'score_okr'],
    systemPrompt: 'You are an OKR management assistant. Help create, track, and review Objectives and Key Results. Provide scoring and progress reports.',
  },

  // === Education (教育) ===
  {
    id: 'flashcard-maker',
    name: 'Flashcard Maker',
    nameZh: '闪卡制作',
    description: 'Create flashcards from text for spaced repetition learning',
    descriptionZh: '从文本生成闪卡，辅助间隔重复学习',
    category: 'education',
    icon: '🃏',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['create_flashcards', 'quiz_me', 'review_deck'],
    systemPrompt: 'You are a flashcard assistant. Extract key concepts from text and create question-answer flashcards for effective spaced repetition learning.',
  },
  {
    id: 'language-tutor',
    name: 'Language Tutor',
    nameZh: '语言老师',
    description: 'Practice languages with conversational exercises',
    descriptionZh: '通过对话练习学外语',
    category: 'education',
    icon: '🗣️',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['practice_conversation', 'correct_grammar', 'vocabulary_quiz'],
    systemPrompt: 'You are a language tutor. Help users practice languages through conversation, correct grammar mistakes gently, and build vocabulary with quizzes.',
  },
  {
    id: 'study-planner',
    name: 'Study Planner',
    nameZh: '学习规划',
    description: 'Create study plans and track learning goals',
    descriptionZh: '制定学习计划，追踪学习目标',
    category: 'education',
    icon: '📐',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['create_plan', 'track_progress', 'suggest_resources'],
    systemPrompt: 'You are a study planning assistant. Create structured study plans, track progress toward learning goals, and suggest relevant resources.',
  },

  // === DevOps (运维) ===
  {
    id: 'log-analyzer',
    name: 'Log Analyzer',
    nameZh: '日志分析',
    description: 'Analyze application logs and find issues',
    descriptionZh: '分析应用日志，发现问题',
    category: 'developer',
    icon: '📋',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['parse_logs', 'find_errors', 'summarize_logs'],
    systemPrompt: 'You are a log analysis assistant. Parse application logs, identify error patterns, highlight anomalies, and suggest root causes.',
  },
  {
    id: 'docker-helper',
    name: 'Docker Helper',
    nameZh: 'Docker 助手',
    description: 'Generate Dockerfiles and docker-compose configs',
    descriptionZh: '生成 Dockerfile 和 docker-compose 配置',
    category: 'developer',
    icon: '🐳',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['generate_dockerfile', 'create_compose', 'optimize_image'],
    systemPrompt: 'You are a Docker assistant. Generate Dockerfiles, docker-compose configurations, optimize image sizes, and troubleshoot container issues.',
  },
  {
    id: 'git-helper',
    name: 'Git Helper',
    nameZh: 'Git 助手',
    description: 'Git operations and commit message generation',
    descriptionZh: 'Git 操作和 commit 信息生成',
    category: 'developer',
    icon: '🔀',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['generate_commit_msg', 'resolve_conflict', 'explain_diff'],
    systemPrompt: 'You are a Git assistant. Generate meaningful commit messages, help resolve merge conflicts, explain diffs, and suggest Git workflows.',
  },

  // === Communication (沟通) ===
  {
    id: 'meeting-summarizer',
    name: 'Meeting Summarizer',
    nameZh: '会议纪要',
    description: 'Summarize meeting notes and extract action items',
    descriptionZh: '总结会议要点，提取行动项',
    category: 'productivity',
    icon: '📋',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['summarize_meeting', 'extract_actions', 'generate_minutes'],
    systemPrompt: 'You are a meeting assistant. Summarize meeting discussions, extract action items with owners and deadlines, and generate formatted meeting minutes.',
  },
  {
    id: 'presentation-builder',
    name: 'Presentation Builder',
    nameZh: 'PPT 助手',
    description: 'Create presentation outlines and talking points',
    descriptionZh: '生成演示文稿大纲和讲解要点',
    category: 'creative',
    icon: '🎬',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['create_outline', 'generate_slides', 'talking_points'],
    systemPrompt: 'You are a presentation assistant. Create structured presentation outlines, generate slide content, and prepare talking points for speakers.',
  },
  {
    id: 'brainstorm',
    name: 'Brainstorm',
    nameZh: '头脑风暴',
    description: 'Facilitate brainstorming sessions with creative techniques',
    descriptionZh: '用创意技法辅助头脑风暴',
    category: 'creative',
    icon: '💡',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['generate_ideas', 'evaluate_ideas', 'mind_map'],
    systemPrompt: 'You are a brainstorming facilitator. Generate creative ideas using techniques like SCAMPER, mind mapping, and lateral thinking. Help evaluate and refine ideas.',
  },
  {
    id: 'legal-assistant',
    name: 'Legal Assistant',
    nameZh: '法律助手',
    description: 'Basic legal knowledge and document drafting',
    descriptionZh: '基础法律知识和文书起草',
    category: 'business',
    icon: '⚖️',
    version: '1.0.0',
    author: 'OPC Team',
    tools: ['draft_document', 'explain_law', 'check_compliance'],
    systemPrompt: 'You are a legal assistant. Help draft basic legal documents, explain legal concepts in plain language, and check for compliance issues. Always recommend consulting a real lawyer for important matters.',
  },
];
