// L3 evolution — discover reusable skills from repeated conversation patterns
import * as fs from 'fs/promises';
import * as path from 'path';
import { randomUUID } from 'crypto';
import type { Message, EvolutionConfig, DeepBrainProvider } from '../core/types';
import type { ModelRouter } from '../providers/router';

interface DiscoveredPattern {
  name: string;
  description: string;
  triggers: string[];
  steps: string[];
}

export async function discoverSkills(
  recentMessages: Message[][],
  router: ModelRouter,
  config: EvolutionConfig,
  brain?: DeepBrainProvider
): Promise<string[]> {
  if (!config.l3.enabled || !config.l3.autoDiscover) return [];
  if (recentMessages.length === 0) return [];

  const provider = router.getProvider('l3');
  const discoverPrompt = `分析以下多轮对话，找出重复出现的任务模式。每个模式输出：
{"name":"skill-name","description":"做什么","triggers":["触发关键词"],"steps":["步骤1","步骤2"]}
将多个模式放在数组中：[{...},{...}]`;

  const conversationSample = recentMessages
    .slice(0, 10)
    .map((msgs, i) =>
      `--- 对话 ${i + 1} ---\n${
        msgs.slice(0, 10).map(m => `[${m.role}]: ${m.content.slice(0, 200)}`).join('\n')
      }`
    )
    .join('\n\n');

  const response = await provider.chat({
    systemPrompt: discoverPrompt,
    messages: [{
      id: randomUUID(),
      role: 'user',
      content: conversationSample,
      timestamp: Date.now(),
    }],
  });

  const patterns = safeParseJSONArray(response.message.content);
  if (patterns.length === 0) return [];

  const skillsDir = '.opc/skills';
  await fs.mkdir(skillsDir, { recursive: true });

  const paths: string[] = [];

  for (const p of patterns) {
    const name = p.name;
    if (typeof name !== 'string' || !name) continue;
    const safeName = name.replace(/[^a-zA-Z0-9-_]/g, '-').toLowerCase();
    const filePath = path.join(skillsDir, `auto-${safeName}.md`);

    await fs.writeFile(filePath, generateSkillMarkdown(p as unknown as DiscoveredPattern), 'utf-8');

    if (brain) {
      await brain.store({
        content: JSON.stringify({
          type: 'skill_record',
          name: safeName,
          description: String(p.description ?? ''),
          filePath,
          status: 'candidate',
        }),
        source: 'l3',
        layer: 'workstation',
        tags: ['skill', 'candidate', safeName],
        embedding: null,
        maturityScore: 0,
        useCount: 0,
        lastUsed: '',
      });
    }

    paths.push(filePath);
  }

  return paths;
}

function generateSkillMarkdown(p: DiscoveredPattern): string {
  const triggers = Array.isArray(p.triggers) ? p.triggers : [];
  const steps = Array.isArray(p.steps) ? p.steps : [];
  return [
    `# ${p.name}`,
    '',
    `## Description`,
    String(p.description ?? ''),
    '',
    `## Triggers`,
    triggers.map(t => `- ${t}`).join('\n') || '- (none)',
    '',
    `## Steps`,
    steps.map((s, i) => `${i + 1}. ${s}`).join('\n') || '1. (none)',
    '',
    `---`,
    `*Auto-generated by OPC L3 Skill Discovery*`,
  ].join('\n');
}

function safeParseJSONArray(text: string): Array<Record<string, unknown>> {
  const arrayMatch = text.match(/\[[\s\S]*\]/);
  if (arrayMatch) {
    try {
      const parsed = JSON.parse(arrayMatch[0]);
      if (Array.isArray(parsed)) return parsed as Array<Record<string, unknown>>;
    } catch { /* fall through */ }
  }
  const objMatch = text.match(/\{[\s\S]*\}/);
  if (objMatch) {
    try {
      const parsed = JSON.parse(objMatch[0]);
      if (typeof parsed === 'object' && parsed !== null && !Array.isArray(parsed)) {
        return [parsed as Record<string, unknown>];
      }
    } catch { /* ignore */ }
  }
  return [];
}
